spring.application.name=security


# Database connection URL, username, and password
spring.datasource.url=jdbc:postgresql://localhost:5433/tutorialseguranca
spring.datasource.username=admin
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#create (apaga tudo e reinicia do zero) / update (ajusta o que mudou) / create-drop (cria inicio apaga quando para) / validate (só valida)/ none (não faz nada)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

#comando openssl rand -hex 32
api.security.token.secret=55e7b9a1d062bfab1a1b1be9688aa69e6717a64be171e89eaf0c944c3ca5b17c